# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        none

# Setup
title:            JoeCamp
tagline:          ''
description:      ''
url:              http://camp.joecode.com

author:
  name:           'Joe Wilson'
  url:            http://joecode.com

paginate:         100

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/joewils/camp.joecode.com
